# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copyto < Formula
  desc "Small console app written in Go that allows you to easily one way sync between folders"
  homepage "https://github.com/aegoroff/copyto"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/copyto/releases/download/v1.3.0/copyto_1.3.0_darwin_amd64.tar.gz"
      sha256 "77919281a2b86d73bdf82310cdaa3c76e8b544c07c5721e55f3642eaf6e2a9ba"

      def install
        bin.install "copyto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aegoroff/copyto/releases/download/v1.3.0/copyto_1.3.0_darwin_arm64.tar.gz"
      sha256 "c1ad86c3e4e324fc450649ec90d18d26e9ef547d3f4ba678a0ec29bdaf0d5769"

      def install
        bin.install "copyto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/copyto/releases/download/v1.3.0/copyto_1.3.0_linux_amd64.tar.gz"
      sha256 "1be1fce42f4e522bbcd938484af310b85795f32a94b8f0d34267cf3b56eb0376"

      def install
        bin.install "copyto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aegoroff/copyto/releases/download/v1.3.0/copyto_1.3.0_linux_armv7.tar.gz"
      sha256 "68ba85e7f1229c2537849ae8146c73959751136c89daf7859cfe7bbf340c3f23"

      def install
        bin.install "copyto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aegoroff/copyto/releases/download/v1.3.0/copyto_1.3.0_linux_arm64.tar.gz"
      sha256 "dd50e562d560509be3f318791da20bd06d0d851b32b247089fe317a66e73eb4d"

      def install
        bin.install "copyto"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/copyto ver")
  end
end
