# This file was generated by GoReleaser. DO NOT EDIT.
class Copyto < Formula
  desc "A small command line app written in Go that allows you to easily one way sync between folders"
  homepage "https://github.com/aegoroff/copyto"
  version "1.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aegoroff/copyto/releases/download/v1.1.3/copyto_1.1.3_darwin_amd64.tar.gz"
    sha256 "ea5bf56aa71917378c8ad84e02bbb99ccd4e03e996df3075c742b4753acc2aea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aegoroff/copyto/releases/download/v1.1.3/copyto_1.1.3_linux_amd64.tar.gz"
    sha256 "eb95608037fe064f54526740ce274112081c452b4fd3c6a760051e52252d63df"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/aegoroff/copyto/releases/download/v1.1.3/copyto_1.1.3_linux_armv7.tar.gz"
    sha256 "61124e1a6fe1cd913a1f749e404e15c5f648cc67a41e65beb6cfbc7f318584af"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/aegoroff/copyto/releases/download/v1.1.3/copyto_1.1.3_linux_arm64.tar.gz"
    sha256 "bcd4dbdd29994d0a2afdeec2ea977beb85928cf9019c1fa08b03a5402988f466"
  end

  def install
    bin.install "copyto"
  end
end
