# This file was generated by GoReleaser. DO NOT EDIT.
class Copyto < Formula
  desc "A small command line app written in Go that allows you to easily one way sync between folders"
  homepage "https://github.com/aegoroff/copyto"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aegoroff/copyto/releases/download/v1.1.0/copyto_1.1.0_darwin_amd64.tar.gz"
    sha256 "f3ca10cc04a13ce0dcee8b909d979614273ad57e60c555c8dd67942ea91ab67d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/copyto/releases/download/v1.1.0/copyto_1.1.0_linux_amd64.tar.gz"
      sha256 "f0532bed15b17951b834236d06585d9052d200c8895541032f50f83502fecf48"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aegoroff/copyto/releases/download/v1.1.0/copyto_1.1.0_linux_arm64.tar.gz"
        sha256 "69589c1cc630de4052fb6658b9c5bafd97cda56110b86f5f439f2ea5725e3d79"
      else
        url "https://github.com/aegoroff/copyto/releases/download/v1.1.0/copyto_1.1.0_linux_armv7.tar.gz"
        sha256 "bc198968f180d3bd349b55c6f9c7fc882f39ae4ccd2a8c79de408af44e187654"
      end
    end
  end

  def install
    bin.install "copyto"
  end
end
