# This file was generated by GoReleaser. DO NOT EDIT.
class Dirstat < Formula
  desc "A small tool that shows selected folder or drive (on Windows) usage statistic"
  homepage "https://github.com/aegoroff/dirstat"
  version "0.10.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aegoroff/dirstat/releases/download/v0.10.7/dirstat_0.10.7_darwin_amd64.tar.gz"
    sha256 "9b330e7b8803281ecb5c2e1af08c30983ec01c4314ae30ecd8f704be3bd4fbf6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/dirstat/releases/download/v0.10.7/dirstat_0.10.7_linux_amd64.tar.gz"
      sha256 "9e0f7269a8700030ee477c9593c43a1be678eeb88061acbc0f39dc9081a5858f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aegoroff/dirstat/releases/download/v0.10.7/dirstat_0.10.7_linux_arm64.tar.gz"
        sha256 "eaba9bbc3156079c09660153f90df64a3a28cfda96d170625584919e8e48e1b7"
      else
        url "https://github.com/aegoroff/dirstat/releases/download/v0.10.7/dirstat_0.10.7_linux_armv7.tar.gz"
        sha256 "4541cc1b4c4f41d6e6641a514c4ae52fdba80dd9aa6d5df42d1340966a63bf16"
      end
    end
  end

  def install
    bin.install "dirstat"
  end
end
