# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Editorconfiger < Formula
  desc "Plain tool to validate and compare .editorconfig files"
  homepage "https://github.com/aegoroff/editorconfiger"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/editorconfiger/releases/download/0.4.2/editorconfiger-0.4.2-x86_64-apple-darwin.tar.gz"
      sha256 "b12f4fc36ab0841c108b2ba46fbba20911898645d6163aeaf89a0d641002cd15"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/editorconfiger/releases/download/0.4.2/editorconfiger-0.4.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bc746c9ed405713675a32b1ffef548ac4f5d76e158656f948224a684bd0faee3"
    end
  end

  def install
    bin.install Dir["*"]
  end

end
