# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Editorconfiger < Formula
  desc "Plain tool to validate and compare .editorconfig files"
  homepage "https://github.com/aegoroff/editorconfiger"
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/editorconfiger/releases/download/v0.1.3/editorconfig-v0.1.3-x86_64-apple-darwin.tar.gz"
      sha256 ""
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/editorconfiger/releases/download/v0.1.3/editorconfig-v0.1.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "editorconfiger"
  end

end
