# This file was generated by GoReleaser. DO NOT EDIT.
class Fg < Formula
  desc "A small commandline app written in Go that allows you to easily group all files in the dir specified into several child directories."
  homepage "https://github.com/aegoroff/fg"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aegoroff/fg/releases/download/v0.2.1/fg_0.2.1_darwin_amd64.tar.gz"
    sha256 "c5620e3fa49830684acba9074f1b34755c313e3ab47bcec6d3fcceaad2aea29c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.1/fg_0.2.1_linux_amd64.tar.gz"
      sha256 "98da7ea9457d0289e26010534b5444fe1ada3b5eea53bf1a4f6d0c41a53df203"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aegoroff/fg/releases/download/v0.2.1/fg_0.2.1_linux_arm64.tar.gz"
        sha256 "11a995bdd20572cfd8366036fbd64bab8eee5a74d2da82b0495266b9bbe218e3"
      else
        url "https://github.com/aegoroff/fg/releases/download/v0.2.1/fg_0.2.1_linux_armv7.tar.gz"
        sha256 "9d54420dfea8b20b2ff5810f4ac7b004af626335eb4d92d5bcc8753edcc2a9c1"
      end
    end
  end

  def install
    bin.install "fgr"
  end
end
