# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fg < Formula
  desc "Small console app written in Go that allows you to easily group all files in the dir specified"
  homepage "https://github.com/aegoroff/fg"
  version "0.2.5"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.5/fg_0.2.5_darwin_amd64.tar.gz"
      sha256 "b569416a0928fcf5730154b6350da3330a924a770790bb4eda5395c1c6483d52"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.5/fg_0.2.5_darwin_arm64.tar.gz"
      sha256 "bf22a33fafc798904c8922a798486e5b098a40d4898154ecc550e63a0b0cf689"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.5/fg_0.2.5_linux_amd64.tar.gz"
      sha256 "9b00e14735f91769edbdb136f8274bae962c5d5ab41db0af2f9fd089baa50cd2"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.5/fg_0.2.5_linux_armv7.tar.gz"
      sha256 "9bf20ada5abe00e6993e3d273c05829504cbfaa14761a2361aa243556f15ae09"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aegoroff/fg/releases/download/v0.2.5/fg_0.2.5_linux_arm64.tar.gz"
      sha256 "67420a30240688b9bc174a79eb1a0c9c1ab7174c120cb1cfe60701c2e1bcc1b9"
    end
  end

  def install
    bin.install "fgr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fgr ver")
  end
end
