# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Grok < Formula
  desc "Regular expressions macro engine. GROK is a tool like UNIX grep on steroids"
  homepage "https://github.com/aegoroff/grok"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/grok/releases/download/0.5.3/grok-0.5.3-x86_64-macos-none.tar.gz"
      sha256 "2f54b82d8859d9766a9226bbebd0d962e4a94c01e5e48c26ffa87aed32d038bf"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aegoroff/grok/releases/download/0.5.3/grok-0.5.3-aarch64-macos-none.tar.gz"
      sha256 "80c52835cc692600746a3884ac442d439d10d95848f6705f1acef39652c25451"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/grok/releases/download/0.5.3/grok-0.5.3-x86_64-linux-musl.tar.gz"
      sha256 "9813dd88822d7556e522ade537e9784ebf7c31f47b754e83017fcaf6f2775ee3"
    end
  end

  def install
    bin.install Dir["*"]
  end

end
