# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Grok < Formula
  desc "Regular expressions macro engine. GROK is a tool like UNIX grep on steroids"
  homepage "https://github.com/aegoroff/grok"
  version "0.2.33"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/grok/releases/download/0.2.33/grok-0.2.33-x86_64-apple-darwin.tar.gz"
      sha256 "f1c88f3b29f4c503c21cd78797b7d360d534c1a9ed5d67da85b68050d7ee6eed"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/grok/releases/download/0.2.33/grok-0.2.33-x86_64-unknown-linux-musl.tar.gz"
      sha256 "486105dbccc098190c88412ee20437d59a29bc546997afe44d9e25372a0d72de"
    end
  end

  def install
    bin.install Dir["*"]
  end

end
