# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Hc < Formula
  desc "Hash Calculator is the console tool that can calculate about 70 cryptographic hashes of strings and files."
  homepage "https://github.com/aegoroff/hc"
  version "6.1.0"
  license "LGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/hc/releases/download/6.1.0/hc-6.1.0-x86_64-unknown-macos-none.tar.gz"
      sha256 "d9d53508192c35e9d49796cb6d570e7e348d117732adbcde02a13dfeb958eac4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aegoroff/hc/releases/download/6.1.0/hc-6.1.0-aarch64-unknown-macos-none.tar.gz"
      sha256 "d451bb31bd33fc15e7d66175b6575bc14d519603ddeb5cd25ef39b479b867ba9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/hc/releases/download/6.1.0/hc-6.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "4455e04b7581fae52996da35fbb158e5279575a8216df7d09af3a077c3e4eb6b"
    end
  end

  def install
    bin.install Dir["*"].select { |f| File.file?(f) && File.executable?(f) }
  end

end
