# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Hc < Formula
  desc "Hash Calculator is the console tool that can calculate about 70 cryptographic hashes of strings and files."
  homepage "https://github.com/aegoroff/hc"
  version "6.1.3"
  license "LGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/hc/releases/download/6.1.3/hc-6.1.3-x86_64-unknown-macos-none.tar.gz"
      sha256 "9ebd9ff334c347a6254ee95594f45784baa5bea5d9d1f85528d6f1fd0550a4e0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aegoroff/hc/releases/download/6.1.3/hc-6.1.3-aarch64-unknown-macos-none.tar.gz"
      sha256 "cdb1b9080d40190bebb1d99f1e560ea10231b2f138021a5dd88d76c22a4a6ba6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/hc/releases/download/6.1.3/hc-6.1.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "62cb58cd5b114fd1b68bd0e18d2c170747e1c6d07d6fd381e5adc83d9c7c12e4"
    end
  end

  def install
    bin.install Dir["*"].select { |f| File.file?(f) && File.executable?(f) }
  end

end
