# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solt < Formula
  desc "Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects"
  homepage "https://github.com/aegoroff/solt"
  version "1.0.6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/aegoroff/solt/releases/download/v1.0.6/solt_1.0.6_darwin_amd64.tar.gz"
    sha256 "4b4354a31e2dcc5c97ff8aa3aaebb3dc99718a197ebe4459678d2553a5cae2a2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aegoroff/solt/releases/download/v1.0.6/solt_1.0.6_linux_amd64.tar.gz"
    sha256 "a59e1c723194663c23ccb883788551db863e1ee97aefdb683e1e7f2fd12e177e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/aegoroff/solt/releases/download/v1.0.6/solt_1.0.6_linux_armv7.tar.gz"
    sha256 "51665610b1432c65112de71793315d06b417da5737317984fb41e75367fce1bb"
  end

  def install
    bin.install "solt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/solt ver")
  end
end
